"""MCP Server — exposes KnowledgeService via 8 agent-friendly tools.

All tools return markdown-formatted strings so the calling agent can render them
directly. Argument shape is flattened (no nested objects, comma-separated lists
for tags/related) to keep the schema easy for LLMs to produce correctly.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from typing import Any

from fastmcp import FastMCP

from mnemo.config import MnemoConfig
from mnemo.db import get_session_factory, init_db
from mnemo.health import detectors as health_detectors
from mnemo.health.dispatcher import format_task_hint, pick_task_for_search
from mnemo.health.hints import hint_from_create_result, hint_from_feedback_result
from mnemo.health.task_store import add_task as _add_health_task
from mnemo.monitor.collector import configure as configure_monitor
from mnemo.monitor.collector import monitor_tool, record_payload
from mnemo.services import feedback_service
from mnemo.services.knowledge_service import KnowledgeService
from mnemo.setup.prompt_template import get_mcp_instructions


logger = logging.getLogger(__name__)

VALID_CLAIM_TYPES: frozenset[str] = frozenset(
    {"fact", "decision", "procedure", "hypothesis"}
)


# Phase 5 task-tracking: task_id is a 32-char lowercase hex uuid4 generated by
# ``HealthTask`` and piggy-backed on search hints. The MCP layer validates the
# shape locally; if ``mnemo.health.tracking`` exposes its own validator we
# defer to it so the two stay in lockstep.
_TASK_ID_RE = re.compile(r"^[0-9a-f]{32}$")


def _validate_task_id(task_id: str | None) -> tuple[str | None, str]:
    """Return ``(clean_task_id, trigger_source)``.

    * Valid hex uuid → (task_id, "search_dispatch")
    * None / invalid  → (None, "agent_initiative")

    Invalid values are silently dropped (never raises) per TASK_TRACKING §3:
    agents must never break because of a malformed tracking token.
    """
    if task_id is None:
        return None, "agent_initiative"
    try:  # prefer the shared validator when tracking module is ready
        from mnemo.health import tracking as _tracking  # type: ignore

        validator = getattr(_tracking, "validate_task_id", None)
        if validator is not None and validator(task_id):
            return task_id, "search_dispatch"
    except Exception:  # noqa: BLE001
        pass
    if isinstance(task_id, str) and _TASK_ID_RE.fullmatch(task_id):
        return task_id, "search_dispatch"
    return None, "agent_initiative"


# ============================================================================
# mnemo MCP 核心提示词(instructions)
# ----------------------------------------------------------------------------
# 【这是什么】下方 instructions 字符串是 mnemo MCP server 对外广播的系统提示词。
# 【发给谁】每一个通过 MCP 连接到 mnemo 的 agent(包括 mteam 所有成员)在会话开始
#           时都会收到这段文字,作为使用 mnemo 工具的行为准则。
# 【驱动什么】agent 的知识库行为——何时 search、何时 create/update、何时
#           feedback——完全由这段提示词驱动。没有它,agent 不会主动用 mnemo。
# 【修改影响】动这里的任何一个字都会实时改变所有连上 mnemo 的 agent 的行为模式,
#           改前务必过方案,改后必须跑回归(scripts/phase3_regression_gate.py)。
#
# ★ 如果你是 mteam 成员 ★
#   这就是你的工作指南。进入任何任务时严格按下面 4 个 STEP 执行:
#     STEP 1 SEARCH  —— 先搜,上下文不完整就是要搜
#     STEP 2 WORK+WRITE —— 边干边记,用户的话是最高优先级事实
#     STEP 3 FEEDBACK —— 用过的知识必须回馈,系统靠这个学习
#     STEP 4 BEFORE RESPOND —— 回话前先自检清单,该写就先写再回
# ============================================================================
mcp: FastMCP = FastMCP(
    "mnemo",
    instructions=get_mcp_instructions(),
)

_service: KnowledgeService | None = None


def set_service(service: KnowledgeService) -> None:
    """Inject the KnowledgeService — used by both the CLI entrypoint and tests."""
    global _service
    _service = service


def _require_service() -> KnowledgeService:
    if _service is None:
        raise RuntimeError(
            "KnowledgeService not initialized — call set_service() before invoking tools"
        )
    return _service


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------

def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [part.strip() for part in value.split(",") if part.strip()]


def _sanitize_claim_type(value: str | None) -> str | None:
    """Whitelist-validate claim_type coming from an agent over MCP.

    Why: agents occasionally paste XML tool-call fragments (e.g.
    ``decision</claim_type>\\n<parameter name=...``) into the value slot
    when hand-producing arguments. Those shards must not reach storage —
    they break downstream rerank (freshness uses claim_type to pick
    lambda) and any filtering by type. Missing / blank stays None so the
    "unspecified" case still works.
    """
    if value is None:
        return None
    trimmed = value.strip()
    if not trimmed:
        return None
    if trimmed in VALID_CLAIM_TYPES:
        return trimmed
    logger.warning(
        "create_knowledge: rejecting invalid claim_type=%r (not in %s); storing as None",
        value,
        sorted(VALID_CLAIM_TYPES),
    )
    return None


def _parse_id_or_title(value: str) -> int | str:
    v = value.strip()
    if v.isdigit():
        return int(v)
    return v


def _format_tags(tags: list[str]) -> str:
    return ", ".join(tags) if tags else "_(none)_"


def _format_summary_entry(index: int, item: dict[str, Any]) -> str:
    claim_type = item.get("claim_type") or "_(unspecified)_"
    status = item.get("status") or "active"
    version = item.get("version")
    status_line = f"{status} · v{version}" if version is not None else status
    conflicts = item.get("conflicts_with") or []

    lines = [
        f"### {index}. {item['title']} (id: {item['id']})",
        f"- **Type:** {claim_type}  ·  **Status:** {status_line}",
        f"- **Tags:** {_format_tags(item.get('tags') or [])}",
        f"- **Scope:** {item.get('scope', 'global')}"
        + (f" / {item['project_name']}" if item.get("project_name") else ""),
    ]
    if conflicts:
        conflict_ids = ", ".join(f"#{cid}" for cid in conflicts)
        lines.append(f"- **Conflicts with:** {conflict_ids}")
    lines.append(f"- **Summary:** {item.get('summary') or '_(empty)_'}")
    return "\n".join(lines) + "\n"


def _format_full_entry(item: dict[str, Any]) -> str:
    related = item.get("related") or []
    claim_type = item.get("claim_type") or "_(unspecified)_"
    status = item.get("status") or "active"
    version = item.get("version")
    status_line = f"{status} · v{version}" if version is not None else status
    parts = [
        f"# {item['title']} (id: {item['id']})",
        "",
        f"- **Type:** {claim_type}  ·  **Status:** {status_line}",
        f"- **Tags:** {_format_tags(item.get('tags') or [])}",
        f"- **Scope:** {item.get('scope', 'global')}"
        + (f" / {item['project_name']}" if item.get("project_name") else ""),
        f"- **Source:** {item.get('source') or '_(none)_'}",
        f"- **Related:** {', '.join(related) if related else '_(none)_'}",
        f"- **Created:** {item.get('created_at') or '_(unknown)_'}",
        f"- **Updated:** {item.get('updated_at') or '_(unknown)_'}",
        "",
        "## Summary",
        item.get("summary") or "_(empty)_",
        "",
        "## Content",
        item.get("content") or "_(empty)_",
    ]
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# tools
# ---------------------------------------------------------------------------

@mcp.tool
@monitor_tool()
async def create_knowledge(
    title: str,
    tags: str,
    summary: str,
    content: str,
    scope: str = "global",
    project_name: str | None = None,
    source: str | None = None,
    claim_type: str | None = None,
    related: str | None = None,
    task_id: str | None = None,
) -> str:
    """Create a new knowledge entry. 适合在本次会话里产生了值得下次复用的经验
    之后调用，典型场景包括：
    - 解决了一个当下搜不到、耗了时间的棘手问题（bug 复盘、陷阱、workaround）。
    - 用户纠正了你之前的做法，并说明了原因 —— 把规则和 Why 一起记下来，
      下次才不会重犯。
    - 做出了一个非显而易见的技术决策或口径约定。
    - 发现了项目/团队内的一个事实性信息（endpoint、owner、外部系统约定）。

    写之前：
    - 先 search 同主题关键词，避免重复写入。如果已存在相近条目，
      改走 update_knowledge 或 supersede，不要叠加。
    - 用 claim_type 标明类型（fact / decision / procedure / hypothesis），
      这会影响 search 的上下文重排。
    - source 尽量填，"自己的经验"也算来源，写清楚比留空好。

    写完之后：
    - 看 response 里的 write_gate：
        exact_duplicate / title_similar / semantic_similar / evidence_weak /
        recommended_action ∈ {"create", "supersede", "review"}
      当推荐是 "supersede" 或 "review" 时，不要硬写，回头 update 匹配到的
      那条 id，或补强证据（content 太短、fact 没 source 都会被拦）。
    - 写入成功后不需要立刻通知用户"我已经记住了"，静默写入即可。

    不适合写入：
    - 当前任务独有的临时上下文（文件路径变量、一次性调试状态）。
    - 已经在 CLAUDE.md 或项目文档里显式规定的东西 —— 记忆是补充，不是复制。
    - 对用户的价值判断（"用户偏好简洁"之类带主观色彩的结论要谨慎）。

    参数：
    - tags：逗号分隔，例 "sqlite,search,中文"。
    - related：逗号分隔的已有条目 title，用来建关系边。
    - scope："global"/"project"/"session"。
    - claim_type：可选，"fact"/"decision"/"procedure"/"hypothesis"。
    - task_id：可选，搜索结果附带的任务 ID，原样传回即可。
      系统据此区分搜索派发回收 vs agent 自发反哺，用于完成率统计。

    Response includes a `write_gate` object:
        { exact_duplicate: null|{id,title},
          title_similar: [{id,title,score}],
          semantic_similar: [{id,title,cosine}],
          evidence_weak: null|{reason},
          recommended_action: "create"|"supersede"|"review" }
    """
    service = _require_service()
    clean_task_id, trigger_source = _validate_task_id(task_id)
    result = await service.create_knowledge(
        title=title,
        summary=summary,
        content=content,
        tags=_split_csv(tags),
        scope=scope,
        project_name=project_name,
        source=source,
        claim_type=_sanitize_claim_type(claim_type),
        related_titles=_split_csv(related),
        task_id=clean_task_id,
        trigger_source=trigger_source,
    )
    gate_info = result.get("write_gate") or {}
    record_payload(
        knowledge_id=result.get("id"),
        recommended_action=gate_info.get("recommended_action"),
        supersedes_id=result.get("supersedes_id"),
        scope=result.get("scope"),
        claim_type=claim_type,
        duplicate_warning=bool(result.get("duplicate_warning")),
    )
    rel = result.get("related") or []
    supersedes = result.get("supersedes_id")
    if supersedes is not None:
        header = (
            f"Created new version #{result['id']} **{result['title']}** "
            f"(supersedes #{supersedes}, version {result.get('version')})"
        )
    else:
        header = f"Created knowledge **{result['title']}** (id: {result['id']})"
    body = (
        f"{header}\n"
        f"- Tags: {_format_tags(result.get('tags') or [])}\n"
        f"- Scope: {result['scope']}"
        + (f" / {result['project_name']}" if result.get("project_name") else "")
        + f"\n- Related: {', '.join(rel) if rel else '_(none)_'}"
    )
    dup = result.get("duplicate_warning")
    if dup:
        body += (
            f"\n- **Duplicate warning:** same content already exists as "
            f"#{dup['id']} ({dup['title']})"
        )
    gate = result.get("write_gate")
    if gate:
        body += "\n\n" + _format_write_gate(gate)
    hint = hint_from_create_result(result)
    if hint:
        body += hint
    return body


def _format_write_gate(gate: dict[str, Any]) -> str:
    """Render the write_gate report into agent-friendly markdown.

    The caller is expected to read ``recommended_action`` first, then drill
    into the specific hits (exact_duplicate / title_similar / semantic_similar /
    evidence_weak / potential_contradiction) to decide whether to supersede,
    update, or review before re-writing. Action is rendered at the top so it
    doesn't get lost below detail lists.
    """
    action = gate.get("recommended_action") or "create"
    action_hint = {
        "create": "safe to keep as a new entry",
        "supersede": "same content already exists — call update_knowledge on the matched id instead",
        "review": "near-duplicate or contradiction detected — re-check before committing",
    }.get(action, "")

    lines = ["## Write-gate report"]
    if action_hint:
        lines.append(f"- **Recommended action:** `{action}` — {action_hint}")
    else:
        lines.append(f"- **Recommended action:** `{action}`")

    exact = gate.get("exact_duplicate")
    if exact:
        lines.append(
            f"- **Exact duplicate (L0):** #{exact['id']} {exact.get('title', '')}"
        )

    title_similar = gate.get("title_similar") or []
    if title_similar:
        parts = ", ".join(
            f"#{t['id']} {t.get('title', '')} ({float(t.get('score', 0)):.2f})"
            for t in title_similar
        )
        lines.append(f"- **Title similar (L1):** {parts}")

    semantic_similar = gate.get("semantic_similar") or []
    if semantic_similar:
        parts = ", ".join(
            f"#{s['id']} {s.get('title', '')} (cos={float(s.get('cosine', 0)):.2f})"
            for s in semantic_similar
        )
        lines.append(f"- **Semantic similar (L2):** {parts}")

    evidence_weak = gate.get("evidence_weak")
    if evidence_weak:
        lines.append(
            f"- **Evidence weak (L3):** {evidence_weak.get('reason', 'unknown')}"
        )

    contradictions = gate.get("potential_contradiction") or []
    if contradictions:
        parts = ", ".join(
            f"#{c['id']} {c.get('title', '')} ({c.get('reason', '')})"
            for c in contradictions
        )
        lines.append(f"- **Potential contradiction (L4):** {parts}")

    return "\n".join(lines)


@mcp.tool
@monitor_tool()
async def search(
    query: str,
    scope: str | None = None,
    project_name: str | None = None,
    limit: int = 20,
    include_archived: bool = False,
    task_context: str | None = None,
    mode: str = "hybrid",
    sort_by: str = "relevance",
) -> str:
    """Full-text search across stored knowledge. This is the first thing to reach
    for when a task touches territory that might have been solved before —
    接到新任务、不确定某个决定是否已有定论、用户追问"我们上次怎么处理的"、
    或准备写一段新经验前都应该先 search 一次。查重是 create_knowledge 的
    隐含前置步骤。

    用完之后：
    - 命中了有用结果 → 直接用结果回答用户，并对用到的那条调用
      feedback_knowledge(signal="helpful")，让排序学到正向信号。
    - 命中了但跟当下场景不符 / 已过时 → 对那条调用
      feedback_knowledge(signal="misleading" 或 "outdated")，并考虑
      update_knowledge 或 archive_knowledge。
    - 摘要不够判断 → 用 get_knowledge 取完整内容，不要凭 summary 猜。
    - 没命中 → 视任务类型决定是解决它再 create_knowledge 记录下来，还是
      放弃搜索、直接做。如果长 query 搜不到，试试缩短到 2-3 个核心词重搜；
      系统会自动尝试缩短重试，但手动缩短效果更精准。

    不建议用在：
    - 用户明确说"不要翻历史，按我说的做" —— 这时候翻记忆只会增加噪声。
    - 纯事实闲聊（今天星期几之类）。
    - 已经在上一次 search 结果里了还反复搜同一个 query。

    参数：
    - scope：可选，"global"/"project"/"session" 过滤。
    - project_name：scope="project" 时的项目名。
    - include_archived：默认隐藏归档条目；排查旧决策时可打开。
    - task_context：可选，"coding"/"debug"/"decision"/"onboarding"/"general"，
      打开 context-aware 重排。传未知值会降级为 "general" 并告警。
    - mode：可选，"hybrid"（默认）/"fts"/"vector"。hybrid 同时走关键词+
      语义+图谱融合排序。fts 纯关键词匹配，适合精确查找。vector 纯语义
      搜索，适合模糊意图。一般不需要手动指定。
    - sort_by：可选，"relevance"（默认）/"time"/"feedback"。relevance 按
      综合相关度排序。time 按创建时间从新到旧。feedback 按使用反馈权重
      排序（被标记 helpful 越多排越前）。
    """
    service = _require_service()
    hits = await service.search(
        query,
        scope=scope,
        project_name=project_name,
        limit=limit,
        mode=mode,
        include_archived=include_archived,
        task_context=task_context,
        sort_by=sort_by,
    )
    top1 = hits[0] if hits else None
    record_payload(
        hits=len(hits),
        mode=mode,
        sort_by=sort_by,
        task_context=task_context,
        scope=scope,
        include_archived=include_archived,
        auto_fallback=bool(top1 and top1.get("auto_fallback")),
        top1_id=(top1 or {}).get("id"),
        top1_score=(top1 or {}).get("rrf_score"),
    )
    if not hits:
        body = (
            f'No results for "{query}". This topic has no prior knowledge yet. '
            f"After you finish this task, consider calling `create_knowledge` "
            f"to record what you learned — the next agent will thank you."
        )
    else:
        lines = [f'## Search Results for "{query}"  ({len(hits)} hits)', ""]
        for i, h in enumerate(hits, start=1):
            lines.append(_format_summary_entry(i, h))
        body = "\n".join(lines)

    task = pick_task_for_search(
        project_name=project_name,
        query=query,
        scope=scope,
    )
    if task:
        body += format_task_hint(task)
    return body


@mcp.tool
@monitor_tool()
async def get_knowledge(id_or_title: str) -> str:
    """Fetch the full text of a knowledge entry by numeric id or exact title.
    search 返回的是摘要，真正要"照着办"或"引用 Why"之前，应该先用
    get_knowledge 把完整内容读出来。

    典型使用时机：
    - search 命中的摘要里提到"see content for details / 完整步骤见正文" ——
      不读正文就执行基本会漏步骤。
    - 知识的 claim_type 是 "decision" 或 "procedure"，需要理解前因后果
      而不仅是结论。
    - 用户追问"为什么是这样" —— Why 一般在 content 里，不在 summary 里。
    - 准备 update_knowledge 之前要先读原文，看哪些字段值得保留、哪些要
      重写。
    - 准备写一条看起来相关的新知识时，先读一下老条目，决定是补充还是新建。

    不需要 get_knowledge 的情形：
    - search 摘要已经足够精确回答用户的问题。
    - 条目 title 暗示它只是个指针（"See X for details"）而目标 X 已经在手。
    - 只是想列一下相关条目标题 —— 用 get_related / search_by_tag 更轻。

    参数：
    - id_or_title：整数 id 或精确 title。title 必须一字不差；
      模糊匹配走 search。

    返回：完整 markdown，包括 tags / scope / source / related / 时间戳 /
    summary / content。
    """
    service = _require_service()
    key = _parse_id_or_title(id_or_title)
    result = await service.get_knowledge(key)
    if result is None:
        record_payload(found=False, lookup_key_type="id" if isinstance(key, int) else "title")
        return f"Knowledge not found: {id_or_title}"
    record_payload(
        found=True,
        knowledge_id=result.get("id"),
        lookup_key_type="id" if isinstance(key, int) else "title",
        claim_type=result.get("claim_type"),
        scope=result.get("scope"),
    )
    return _format_full_entry(result)


@mcp.tool
@monitor_tool()
async def update_knowledge(
    id: int,
    title: str | None = None,
    tags: str | None = None,
    summary: str | None = None,
    content: str | None = None,
    task_id: str | None = None,
) -> str:
    """Update fields on an existing knowledge entry. 适合在原有知识基础上
    做增量修正 —— 补充遗漏、纠正错字、加更多 tag、扩写 summary。
    语义级的变化（结论反了、适用场景变了）由 service 层判定是否触发
    supersede 新版本，调用方不需要自己分辨。

    典型使用时机：
    - feedback 标了 "misleading" 之后，补强 content 把 Why 说清楚。
    - feedback 标了 "outdated" 但只是细节过期（比如路径变了），
      原则仍然成立 —— 修细节比重写快。
    - 新增 related 关系，把这条和新写的知识连起来。
    - tag 体系演化，把老条目也补上新 tag 方便检索。

    写之前：
    - 先 get_knowledge 读一遍原文，决定"保留什么、改什么"，不要凭
      summary 就改 content。
    - 想好：这是小修还是结论反转？如果是反转，直接 update 是合理的，
      service 会根据变化幅度决定是否产生新版本（supersedes_id）。

    写之后：
    - 看返回里有没有 supersedes_id —— 有的话说明新建了一条版本链，旧
      那条仍然可查；没的话是原地修改。
    - 不需要再 create 一条"已修正"说明。

    只传你想改的字段。完全不传字段会直接返回 "No fields to update."。

    参数（全部可选）：
    - title / tags / summary / content。tags 用逗号分隔。
    - task_id：可选，搜索结果附带的任务 ID，原样传回即可。
      系统据此统计 search 派发的维护任务被实际执行的比例。
    """
    service = _require_service()
    clean_task_id, trigger_source = _validate_task_id(task_id)
    fields: dict[str, Any] = {}
    if title is not None:
        fields["title"] = title
    if tags is not None:
        fields["tags"] = _split_csv(tags)
    if summary is not None:
        fields["summary"] = summary
    if content is not None:
        fields["content"] = content
    if not fields:
        record_payload(knowledge_id=id, noop=True, fields_changed=0)
        return "No fields to update."

    if clean_task_id is not None:
        fields["task_id"] = clean_task_id
    fields["trigger_source"] = trigger_source
    result = await service.update_knowledge(id, **fields)
    rel = result.get("related") or []
    supersedes = result.get("supersedes_id")
    record_payload(
        knowledge_id=result.get("id", id),
        supersedes_id=supersedes,
        fields_changed=len(fields),
        changed_keys=sorted(fields.keys()),
    )
    header = (
        f"Created new version #{result['id']} **{result['title']}** "
        f"(supersedes #{supersedes}, version {result.get('version')})"
        if supersedes is not None
        else f"Updated knowledge **{result['title']}** (id: {result['id']})"
    )
    return (
        f"{header}\n"
        f"- Fields changed: {', '.join(fields.keys())}\n"
        f"- Tags: {_format_tags(result.get('tags') or [])}\n"
        f"- Related: {', '.join(rel) if rel else '_(none)_'}"
    )


@mcp.tool
@monitor_tool()
async def delete_knowledge(id: int) -> str:
    """Delete a knowledge entry by id. Returns a message indicating whether it existed."""
    service = _require_service()
    deleted = await service.delete_knowledge(id)
    record_payload(knowledge_id=id, deleted=bool(deleted))
    if deleted:
        return f"Deleted knowledge id {id}."
    return f"No knowledge with id {id}."


@mcp.tool
@monitor_tool()
async def archive_knowledge(
    id: int | None = None,
    reason: str | None = None,
    task_id: str | None = None,
) -> str:
    """Archive a knowledge entry — 把 status 从 "active" 改成 "archived"，并
    写入一条审计事件。归档不是删除，条目仍然可以用 get_knowledge /
    get_related 取出，也能通过 unarchive_knowledge 恢复；只是默认从
    search 里藏起来，减少噪声。

    典型使用时机：
    - 知识被更新更准确的条目取代（新条目的 supersedes_id 已经指向它），
      旧版不再需要出现在搜索里。
    - 外部事实变了，整条知识不再成立 —— 和 "outdated" feedback 不同，
      outdated 说的是"需要修"，archive 说的是"不用再看了"。
    - 项目/模块下线，相关知识失去上下文。
    - 用户或团队决定"这条结论作废"，哪怕代码层面还能跑。

    归档前：
    - 最好先 search 一下，确认没有其它文档正引用这条 title。
    - 给一个清晰的 reason —— "superseded by #123"、"module removed in
      2026-04"、"decision reversed in team meeting" 都比空着好。审计事件
      会把 reason 一起写下来，将来排查决策变迁时要靠它。

    不要归档：
    - 只是临时不想在搜索里看见 —— 那是 tag / scope 的职责，不是归档。
    - 知识只是"不全"或"该更新" —— 走 update_knowledge。
    - 还没 supersede 的旧决策在归档前先确认：未来真的不会再被引用吗？
      如果有"历史决策为什么当时是这样"的追溯价值，保留并补一条说明更好。

    要恢复：unarchive_knowledge(id) 即可，反向操作。

    参数：
    - id：必填。但在 state_machine_enabled=False 时会被 feature flag 先
      拦截并返回 {"success": False, "reason": "feature_disabled"}。
    - reason：可选但强烈建议填。
    - task_id：可选，搜索结果附带的任务 ID，原样传回即可。
      系统据此区分搜索派发归档 vs agent 自发归档，用于完成率统计。

    ``id`` is nominally required; declared optional so the state-machine
    feature flag can veto the call before argument validation
    (see ``tests/test_feature_flags.py`` Constraint 4).
    """
    service = _require_service()
    cfg = getattr(service, "_config", None)
    if cfg is not None and not getattr(cfg, "state_machine_enabled", True):
        record_payload(knowledge_id=id, status="skipped", feature_disabled=True)
        return json.dumps({"success": False, "reason": "feature_disabled"})
    if id is None:
        record_payload(status="error", error_type="missing_id")
        return json.dumps({"success": False, "reason": "missing_id"})
    clean_task_id, trigger_source = _validate_task_id(task_id)
    result = await service.archive_knowledge(
        id,
        reason=reason,
        task_id=clean_task_id,
        trigger_source=trigger_source,
    )
    success = bool(result.get("success"))
    record_payload(
        knowledge_id=id,
        success=success,
        has_reason=bool(reason),
        failure_reason=result.get("reason") if not success else None,
    )
    if not success:
        err = result.get("reason") or result.get("error") or "unknown error"
        return f"Archive failed for id {id}: {err}"
    parts = [f"Archived knowledge id {id}."]
    if reason:
        parts.append(f"Reason: {reason}")
    return "\n".join(parts)


@mcp.tool
@monitor_tool()
async def unarchive_knowledge(id: int) -> str:
    """Restore an archived knowledge entry (status='archived' → 'active')."""
    service = _require_service()
    result = await service.unarchive_knowledge(id)
    success = bool(result.get("success"))
    record_payload(knowledge_id=id, success=success)
    if not success:
        err = result.get("error") or "unknown error"
        return f"Unarchive failed for id {id}: {err}"
    return f"Unarchived knowledge id {id}."


@mcp.tool
@monitor_tool()
async def feedback_knowledge(
    knowledge_id: int,
    signal: str,
    reason: str | None = None,
    actor: str = "agent:unknown",
    task_id: str | None = None,
) -> str:
    """Record agent feedback on a knowledge entry. 这是 search / get_knowledge
    之后的收尾动作 —— 用过一条知识，就得留下一次反馈，知识库才知道哪些
    条目在真实工作里"扛得住"。不反馈等于白用。

    三种 signal 的判断：
    - "helpful"：这条知识直接帮你回答/解决了当前问题，不需要改写。
    - "misleading"：这条知识和当下场景不符、结论有偏差、或 Why 没解释清楚
      导致你一开始走错了。reason 里写明"哪里误导了"，下次才能修。
    - "outdated"：内容曾经对，但已被新决策/新代码/新外部约定推翻。
      典型信号是"这里提到的文件/函数/接口不存在了"。之后一般跟着
      update_knowledge 或 archive_knowledge。

    什么时候反馈：
    - 在回答用户 **之后**、而不是读到知识的瞬间 —— 要用真实结果判断。
    - 每次搜索命中并用到的条目都该反馈，哪怕只是 helpful。
    - 对于摘要不够又没点开 get_knowledge 的条目，不用反馈。

    什么时候不反馈：
    - 只是扫了一眼 search 结果、没真的用 —— 不要强行刷好评。
    - 24 小时内对同一条 (actor, knowledge_id) 已经反馈过 —— 有去重锁，
      重复调用会被拒。

    参数：
    - signal："helpful" / "misleading" / "outdated"。
    - reason：自由文本，建议写具体，空写也行但信息量低。
    - actor：调用方身份（用于 24h dedup 的去重键）。默认 "agent:unknown"，
      多 agent 场景建议显式传 "agent:<role>"。
    - task_id：可选，搜索结果附带的任务 ID，原样传回即可。
      系统据此区分搜索派发反馈 vs agent 自发反馈，用于完成率统计。

    当 feedback_loop_enabled=False 时返回
    {"success": False, "reason": "feature_disabled"} 且不写事件。
    """
    service = _require_service()
    cfg = getattr(service, "_config", None) or MnemoConfig()
    if not getattr(cfg, "feedback_loop_enabled", True):
        record_payload(
            actor=actor,
            knowledge_id=knowledge_id,
            signal=signal,
            status="skipped",
            feature_disabled=True,
        )
        return json.dumps({"success": False, "reason": "feature_disabled"})

    clean_task_id, trigger_source = _validate_task_id(task_id)
    result = await service.feedback_knowledge(
        knowledge_id=knowledge_id,
        signal=signal,
        reason=reason,
        actor=actor,
        task_id=clean_task_id,
        trigger_source=trigger_source,
    )
    record_payload(
        actor=actor,
        knowledge_id=knowledge_id,
        signal=signal,
        success=bool(result.get("success")),
        deduped=bool(result.get("deduped") or result.get("already_recorded")),
        reason_len=len(reason) if reason else 0,
    )
    if signal == "misleading" and result.get("success"):
        try:
            async with service._session_factory() as detect_session:
                for task in await health_detectors.detect_high_misleading(
                    detect_session, knowledge_id
                ):
                    _add_health_task(task)
        except Exception as e:  # noqa: BLE001
            logger.warning(
                "health P1-1 detector failed kid=%s: %s", knowledge_id, e
            )
    payload = json.dumps(result, default=str)
    hint = hint_from_feedback_result(result, knowledge_id)
    if hint:
        payload += hint
    return payload


@mcp.tool
@monitor_tool()
async def get_related(id_or_title: str, depth: int = 1) -> str:
    """Traverse the relation graph from a knowledge entry.

    - depth: how many hops to follow (default 1)
    """
    service = _require_service()
    key = _parse_id_or_title(id_or_title)
    neighbors = await service.get_related(key, depth=depth)
    record_payload(
        hits=len(neighbors),
        depth=depth,
        lookup_key_type="id" if isinstance(key, int) else "title",
        knowledge_id=key if isinstance(key, int) else None,
    )
    if not neighbors:
        return f"No related knowledge found for {id_or_title} (depth={depth})."
    lines = [
        f"## Related knowledge for {id_or_title} (depth={depth})",
        f"_{len(neighbors)} neighbor(s)_",
        "",
    ]
    for i, n in enumerate(neighbors, start=1):
        lines.append(_format_summary_entry(i, n))
    return "\n".join(lines)


@mcp.tool
@monitor_tool()
async def list_tags(scope: str | None = None) -> str:
    """List every distinct tag, optionally filtered by scope."""
    service = _require_service()
    tags = await service.list_tags(scope=scope)
    record_payload(tag_count=len(tags), scope=scope)
    if not tags:
        scope_label = f" in scope '{scope}'" if scope else ""
        return f"No tags found{scope_label}."
    header = "## All tags" + (f" (scope: {scope})" if scope else "")
    return header + "\n" + "\n".join(f"- {t}" for t in tags)


@mcp.tool
@monitor_tool()
async def search_by_tag(
    tags: str,
    scope: str | None = None,
    limit: int = 20,
) -> str:
    """Find knowledge entries that carry ALL of the given tags.

    - tags: comma-separated list (e.g. "python,async")
    """
    service = _require_service()
    tag_list = _split_csv(tags)
    if not tag_list:
        record_payload(hits=0, tag_count=0, scope=scope, status="error", error_type="empty_tags")
        return "No tags provided."
    hits = await service.search_by_tag(tag_list, scope=scope, limit=limit)
    record_payload(hits=len(hits), tag_count=len(tag_list), scope=scope)
    if not hits:
        return f"No knowledge found with tags: {', '.join(tag_list)}"
    lines = [
        f"## Knowledge with tags: {', '.join(tag_list)}  ({len(hits)} hits)",
        "",
    ]
    for i, h in enumerate(hits, start=1):
        lines.append(_format_summary_entry(i, h))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# entrypoint
# ---------------------------------------------------------------------------

async def _bootstrap() -> None:
    config = MnemoConfig()
    await init_db(config)
    factory = get_session_factory(config)
    from mnemo.services.embedding_service import EmbeddingService
    embedding = EmbeddingService(config)
    set_service(KnowledgeService(session_factory=factory, embedding_service=embedding))
    configure_monitor(session_factory=factory, enabled=True)


def main() -> None:
    """Sync entrypoint registered as the console script `mnemo-mcp`."""
    import sys

    if len(sys.argv) > 1 and sys.argv[1] in ("--version", "-V"):
        from importlib.metadata import PackageNotFoundError, version

        try:
            ver = version("m-nemo")
        except PackageNotFoundError:
            try:
                ver = version("mnemo")
            except PackageNotFoundError:
                ver = "0.1.0"
        print(f"mnemo-mcp {ver}")
        return

    asyncio.run(_bootstrap())
    mcp.run()


if __name__ == "__main__":
    main()
